### ISSUE TITLE
Accordion and sliders not working in JointsWP demo or my instance

### ISSUE THREAD

**Issue by rgilman** [JeremyEnglert/JointsWP#359] opened 2018-09-26 01:40 UTC
Hi Jeremy,

After they didn't work on my dev site based on JointsWP, I checked [your demo](http://jointswp.com/demo/) and couldn't get them to work in Chrome, FireFox or Safari.

Any idea as to what's broken?

Otherwise, it proving to be a great starter site. Thanks for the work you've put into it.

**Comment by garrett-eclipse** [comment] 2018-10-24 08:19
Hi @rgilman 

I took at look at the demo and realized the issue here is the foundation version on the demo site updated but the accordion didn't update to match. In Foundation 6.4.3 the `data-accordion-item` attribute was added/required on the `.accordion-item`'s;
`<li class="accordion-item is-active" data-accordion-item>`
Reference - https://foundation.zurb.com/sites/docs/accordion.html

Taking the accordion from the demo into a local instance here I reproduced your issue and then applied the missing attribute which fixed it for me. Give it a try and reopen is still an issue.

As to the sliders I wasn't sure if you meant the range slider or orbit slider, but assume the issue is probably a format issue so would follow the Foundation docs;
Range Slider - https://foundation.zurb.com/sites/docs/slider.html
Order Carousel - https://foundation.zurb.com/sites/docs/orbit.html

@JeremyEnglert if you want to fix the demo for JWP5 see above.

I'm going to close this as the theme itself doesn't provide markup for these Foundation features.

**Closed by garrett-eclipse** 2018-10-24 08:19 UTC
