### ISSUE TITLE
Can't compile style.scss when editing _settings.scss?

### ISSUE THREAD

**Issue by ViPeRx007** [JeremyEnglert/JointsWP#140] opened 2015-12-03 23:07 UTC
I've got a fresh Wordpress install with JointsWP added. I just tried to make a simple change to the $primary-color variable in the _settings.scss file and, when I save it, Prepros gives me an error that it can't compile style.scss. I never seemed to have any issues before, but this is my first time with the latest (Foundation 6) version.

I even reverted the _settings.scss file back to the original, tried to save it, and it gives me the same error.

Reading the error log says this:

Syntax error: Functions can only contain variable declarations and control directives.
        on line 37 of ..\..\vendor\foundation-sites\scss\grid\_column.scss
        from line 26 of ..\..\vendor\foundation-sites\scss\grid\_grid.scss
        from line 15 of ..\..\vendor\foundation-sites\scss\foundation.scss
        from line 21 of style.scss
  Use --trace for backtrace.

Thanks in advance for any assistance.

**Comment by JeremyEnglert** [comment] 2015-12-08 04:29
I'm not familiar with Prepos. Do you get the same error with a blank Foundation install, or is this JointsWP specific? 

The error looks like it is having issues with some of the Foundation files.

**Comment by doubleedesign** [comment] 2015-12-30 12:03
Not a JointsWP-specific issue, I am having the same issue with another starter theme. I also use Prepros. It seems to have a problem with the `@error` lines in the `grid-column` function in `_column.scss`. I have commented these out and can now compile successfully. Of course this is a temporary solution, it'd be preferable to keep them in, but I'm not sure how to properly fix it.

**Comment by JeremyEnglert** [comment] 2015-12-30 15:56
@doubleedesign, it may be worth opening this as an issue on the Foundation 6 repo as well.

I'd also contact Prepos to see if they have any plans on updating to a new version of Sass. 

I also highly recommend checking out Gulp: http://jointswp.com/docs/gulp/

**Comment by doubleedesign** [comment] 2016-01-01 14:07
I just downloaded the trial of the latest version of Prepros, and the error doesn't occur :)
 I was using 4.0.1 which is fairly old. The latest is 5.10.1 which runs SASS 3.4.20.

**Comment by JeremyEnglert** [comment] 2016-02-25 23:30
Looks like this was an error caused by an older version of Prepos. Closing.

**Closed by JeremyEnglert** 2016-02-25 23:30 UTC
