### ISSUE TITLE
Image Remove Watch Task

### ISSUE THREAD

**Issue by jackfearing** [JeremyEnglert/JointsWP#306] opened 2017-12-28 18:05 UTC
Since the new optimize task places images into the parent images folder from the src folder, is there was a way to setup a remove task which watches the src folder (located inside the images folder) and if the image is not in the src folder then remove it from the images folder?

**Comment by garrett-eclipse** [comment] 2017-12-28 18:21
I don't have time for a PR right now but here's documentation on how this could be accomplished;
https://gulpjs.org/recipes/handling-the-delete-event-on-watch

**Comment by jackfearing** [comment] 2018-01-02 22:00
Thanks however I'm a little lost with this method. If you have time in the future, I would greatly appreciate your help with the solution.

**Comment by garrett-eclipse** [comment] 2018-01-03 02:59
Hey @jackfearing 

I'll give it a stab here, I'm no gulp expert though so not sure if it'll work first try...

At the top of the gulpfile.js you'll find some global variables;
```
var gulp  = require('gulp'),
    gutil = require('gulp-util'),
    browserSync = require('browser-sync').create(),
    filter = require('gulp-filter'),
    plugin = require('gulp-load-plugins')();
```
*May not be exact...

In these globals you'll also need the del and path so update like;
```
var gulp  = require('gulp'),
    gutil = require('gulp-util'),
    browserSync = require('browser-sync').create(),
    filter = require('gulp-filter'),
    del = require('del'),
    path = require('path'),
    plugin = require('gulp-load-plugins')();
```

Then within the watch and browsersync task you'll find the following line;
`gulp.watch(SOURCE.images, gulp.parallel('images'));`

If we update this to pipe the watcher into a variable then we can do the change event on that so update the above line wherever you find it with;
`var imageWatcher = gulp.watch(SOURCE.images, gulp.parallel('images'));`

Then right after that within the same task setup a watcher event for the change;
```
  imageWatcher.on('change', function (event) {
    if (event.type === 'deleted') {
      var filePathFromSrc = path.relative(path.resolve(SOURCE.images), event.path);
      var destFilePath = path.resolve(ASSETS.images, filePathFromSrc);
      del.sync(destFilePath);
    }
  });
```
*I updated this with SOURCE.images and ASSETS.images but can't confirm if that's right.

I'll be amazed if that works first try. Let me know how it goes and if stuck share the gulpfile.js and any errors logged.

Cheers

**Comment by jackfearing** [comment] 2018-01-05 20:00
Thanks Garrett. The code doesn't error which is great however I'm not sure what the result should be. The images directory is the same and no other folders are created inside of it with the original images or is that something I need to manually create?

**Comment by garrett-eclipse** [comment] 2018-01-05 21:16
Hey @jackfearing 
Can you send me your gulpfile.js and I'll proof it here.

But with this setup in the browsersync or watch commands if you run those tasks `gulp watch` or `gulp browsersync` then when you go and remove an image from the source images folder it should get removed from the rendered assets folder.

Basically nothing should happen until you actually remove source images and have those tasks running


Hope that makes sense,
Cheers

**Comment by jackfearing** [comment] 2018-01-05 21:19
Sure thing -- attached is the gulp file.
[gulpfile.js.zip](https://github.com/JeremyEnglert/JointsWP/files/1607917/gulpfile.js.zip)

**Comment by garrett-eclipse** [comment] 2018-01-05 22:34
Good stuff, looks right to me.

So if you're watching or browsersyncing and add a new image to your source folder does it get minified and copied into the assets folder?
Source - images: 'assets/images/**/*',
Assets - images: 'assets/images/',
*Basically if you add an image to a subfolder of assets/images does it get optimized and copied into assets/images?

If that holds true and your imagemin is working then go and delete that same test image from the source folder while still watching/browsersyncing and see if it's removed from the assets folder?

If it is then voila it's working properly.

Fingers crossed.
Cheers

**Comment by jackfearing** [comment] 2018-01-06 01:32
This is how I currently have my folder structure setup but the image is not deleting. Should I be doing something different? /assets/images/src

![screen shot 2018-01-05 at 5 32 11 pm](https://user-images.githubusercontent.com/6834687/34634976-639bdd72-f23e-11e7-9a26-c64391428bf6.png)

**Comment by garrett-eclipse** [comment] 2018-01-06 01:59
That's perfect @jackfearing so when you run the `gulp images` command it should optimize that image and duplicate it up into just the images folder (one level up). Then if you run `gulp watch` or `gulp browsersync` and go remove that image in assets/images/src it should detect that and remove the duplicate within the assets/images folder.
Fingers crossed

**Comment by jackfearing** [comment] 2018-01-06 18:14
That makes sense however when I add images to the src folder nothing happens. No images get moved or deleted which is where I'm stuck at now...

**Comment by garrett-eclipse** [comment] 2018-01-08 03:49
Are you actively doing either `gulp watch` or `gulp browsersync`?
And if so do anything log or kick off in the terminal when you add images, or remove?

**Comment by jackfearing** [comment] 2018-01-10 23:14
I'm doing a gulp browsersync to kick everything off. When I add or remove images from the directory the terminal windows shows some tasks being run but it looks like the gulp-imagemin =0. See attached image.

![screen shot 2018-01-10 at 3 13 02 pm](https://user-images.githubusercontent.com/6834687/34800505-e87d44d0-f618-11e7-92c0-7cbe627a67da.png)

**Comment by garrett-eclipse** [comment] 2018-01-10 23:37
Hey @jackfearing that's strange, I see a couple issues on the web with that error but no resolution.

Comparing your gulpfile to master I found in your images task there's this line that isn't present in master;
`.pipe(plugin.newer(ASSETS.images))`
*I'm not sure why that's present or what it does.

Also I found you're double watching files in your browsersync as not only do you list styles, login, scripts and images in the files array but you're also watching them. 
So I would also try removing all but SOURCE.php from the files array.

Hopefully that moves us forward a bit.

When you do run it and place images in src, do they get duplicated into the folder above that? Have you tried removing a src/ image and see if it removes from the parent folder?

**Comment by jackfearing** [comment] 2018-01-10 23:50
So to make things simple I grabbed the latest version of the gulp file from master and added back in the code from the above comment. Then re-ran terminal / browsersync, now the images task loops.... Attached my latest gulp file and here is a screen shot of the terminal. Not sure what could be causing this. Your instructions seemed to make sense.

**Download Gulp File:**
[gulpfile.js.zip](https://github.com/JeremyEnglert/JointsWP/files/1620763/gulpfile.js.zip)

![screen shot 2018-01-10 at 3 49 25 pm](https://user-images.githubusercontent.com/6834687/34801483-ddff2c58-f61d-11e7-9c30-e09a998a4302.png)

**Comment by garrett-eclipse** [comment] 2018-01-10 23:54
Hmm, this looping might be caused by the SOURCE encompassing the ASSETS folder so it's reoptimizing images over and over. because you already have sources images in /assets/images/src I'd suggest updating this line;
`images: 'assets/images/**/*',`
To be more specific;
`images: 'assets/images/src/**/*',

This should hopefully avoid the looping.

**Comment by jackfearing** [comment] 2018-01-10 23:59
Well good news, after the code update above, when I add images to src folder is minifies and adds them to the parent folder above. See attached screen shot. However if I remove the images form the src folder the images in the parent folder remain. Does this mean the DEL function needs to be updated as well?

![screen shot 2018-01-10 at 3 59 09 pm](https://user-images.githubusercontent.com/6834687/34801771-3b29ccac-f61f-11e7-8afd-6e2140fcc8ec.png)

**Comment by garrett-eclipse** [comment] 2018-01-11 00:05
Nice that's a step forward. Yes seems there's still an issue with the del command.
Was there anything logged?

I believe maybe the npm package for del might need to be installed when I look at this package;
https://github.com/sindresorhus/del

Try running `npm install --save del` and `npm install --save path` to install the two new dependencies, then do the browsersync again.
If this is the case then when we do a PR for this task we'll have to make sure to update package.json with the appropriate dependencies.

**Comment by jackfearing** [comment] 2018-01-11 00:10
Nothing gets logged when items are removed from the parent directory. Only time the terminal shows anything is when the image is added and/or removed from the SRC directory. Also, I re-installed DEL and PATH with the same result.

**Comment by garrett-eclipse** [comment] 2018-01-11 00:15
What is it logging when you remove images from the src directory? That's when they should remove from assets. When you remove something from assets and not src then you need to manually run the images task to restore it into the assets folder. This del task is to remove images form assets that were removed from src.

**Comment by jackfearing** [comment] 2018-01-11 00:22
Here is a screen shot of what I see in terminal... Does this help? Also, after I removed the images from the SRC directory and ran the 'IMAGES' task nothing happens. 

![screen shot 2018-01-10 at 4 21 51 pm](https://user-images.githubusercontent.com/6834687/34802420-68959ad8-f622-11e7-9626-b06dd8a5795b.png)

**Comment by garrett-eclipse** [comment] 2018-01-11 00:33
ya the images task doesn't do any deletes for you sadly, it should maybe do a clean but then the three images at that level would vanish as they aren't in src (the login-logo.png, etc.). And sadly not much to go on there so why don't you package up the entire theme for me and I'll try running the commands locally so I can play with the del command, etc. Thanks

**Comment by jackfearing** [comment] 2018-01-11 00:37
That would be great - thanks. Here is the link to download the theme. 

**Download:** https://ws.onehub.com/files/7o5skls8

**Comment by garrett-eclipse** [comment] 2018-01-11 01:13
Thanks, I've got it running.
I see this as well - gulp-imagemin: Minified 0 images
*This apparently happens when the images are already minified so there's nothing to do, but it does copy them to assets/images

Also I ran into issue #279 here so think we have to look at dependencies (@JeremyEnglert I think we may need to look into including babel-core in the package.json). And also on the dependencies thing I found gulp-jshint is missing the peerdependency of jshint@2.x so @JeremyEnglert please look at that as well.

And as to the delete I see it's not currently working and fails silently... so I'll pick that up later cause I have to head home for the night.

**Comment by garrett-eclipse** [comment] 2018-01-12 06:22
@jackfearing I've followed many threads with no luck here sadly on the delete command. I think as we're moving to separate the source and destination that I'll revisit this at that point. And the other options I found was doing a directory clear on changes so all compressed images are wiped and then only remaining source images are recompressed, it's not really a delete but does the same thing. Only issue with that is because src is under assets/images they'd be purged as well, and when we do segregate to avoid that we'll have to be sure the apple-icon-touch.png, login-logo.png and win8-tile-icon.png all exist in the source as currently they're only present in the assets/images so would get wiped and lost.

**Comment by jackfearing** [comment] 2018-01-12 16:51
That makes sense @garrett-eclipse and thanks for spending the time to look into this. I can't remember but I thought the old joints or maybe it was another theme has the assets, script and css broken out into source folders then when gulp ran it processed them into a compressed minified folders which made since (dev/prod.). I'm looking forward to seeing the next updates to joints :)

**Comment by jackfearing** [comment] 2018-04-16 23:42
Hi @garrett-eclipse, just following up to see if there has been any movement on this. I recently saw the update to the gulp.js in which the images were being optimized in the src folder but was wondering if removing the images that aren't in the src file after optimization is still doable.

**Comment by JeremyEnglert** [comment] 2018-10-14 23:33
We're keeping this "as is" for now. However, in JointsWP 6, we have separated "source" files from the final "assets".

**Closed by JeremyEnglert** 2018-10-14 23:33 UTC
