### ISSUE TITLE
Top Bar, data-close-delay issue

### ISSUE THREAD

**Issue by xron89** [JeremyEnglert/JointsWP#207] opened 2016-10-09 13:35 UTC
By default the topbar/title bar drop down <ul> element has a delay whereby after a hover action the list is still displayed. After reading the foundation documentation it states that you can add the `data-close-delay="0"` tag to the ul to change the delay. 

Inside `assets/functions/menu.php` I added this data tag to the items_wrap ul but theres still a delay.

Any help removing this?

```

// The Top Menu
function joints_top_nav() {
     wp_nav_menu(array(
        'container' => false,                           // Remove nav container
        'menu_class' => 'vertical medium-horizontal menu',       // Adding custom nav class
        'items_wrap' => '<ul id="%1$s" class="%2$s" data-close-delay="0" data-responsive-menu="accordion medium-dropdown">%3$s</ul>',
        'theme_location' => 'main-nav',                 // Where it's located in the theme
        'depth' => 5,                                   // Limit the depth of the nav
        'fallback_cb' => false,                         // Fallback function (see below)
        'walker' => new Topbar_Menu_Walker()
    ));
} 
```

**Comment by fluidjunction** [comment] 2016-10-21 21:38
Hey xron89,

I wasn't able to find that option in the docs but I did find one that worked great. 

Try this instead: `data-closing-time="0"`

Let me know if it works for you.

**Comment by xron89** [comment] 2016-10-23 21:19
Hi, the problem is the dropdown is created dynamically via the wordpress menu interface. This means I don't actually have a nested `<ul>` tag to apply this data attribute too. Of course I could possibly look at appending this data attribute via jquery but there must be a cleaner way?

Surely?

**Comment by fluidjunction** [comment] 2016-10-24 16:11
Hey xron89,

If I'm reading your original post correctly then there's definitely a cleaner way and it's using the same code you provided with a different option.

If you're trying to remove the hover delay of a submenu you could use the data-option I provided from the docs above. So, for example, by default it looks like if I hover over a menu item that has a submenu and then move away from it then the submenu hover delay lasts 1 second.

If I add `data-closing-time="0"` instead of `data-close-delay="0"` to the items_wrap ul then the hover delay would be removed and the submenu would disappear instantly.

Here's the code block that works for me and I didn't need to worry about applying it to specific child ul's. It just works :-)

`// The Top Menu
function joints_top_nav() {
	 wp_nav_menu(array(
        'container' => false,                           // Remove nav container
        'menu_class' => 'vertical medium-horizontal menu',       // Adding custom nav class
        'items_wrap' => '<ul id="%1$s" class="%2$s" data-responsive-menu="accordion medium-dropdown" data-closing-time="0">%3$s</ul>',
        'theme_location' => 'main-nav',          // Where it's located in the theme
        'depth' => 5,                                        // Limit the depth of the nav
        'fallback_cb' => false,                         // Fallback function (see below)
        'walker' => new Topbar_Menu_Walker()
    ));
}`

Let me know if this helps.

**Comment by fluidjunction** [comment] 2016-11-09 19:06
@xron89

Curious if it worked for you as it did for me.

Any feedback would be great :-)

**Comment by JeremyEnglert** [comment] 2016-11-13 04:51
@fluidjunction, I can confirm that worked great! Awesome solution.

**Closed by JeremyEnglert** 2016-11-13 04:51 UTC
