### ISSUE TITLE
"Error: no mixin named breakpoint"

### ISSUE THREAD

**Issue by BenQuirk** [JeremyEnglert/JointsWP#394] opened 2019-02-05 19:48 UTC
Feel like I'm missing something basic here. 

When I do something like this in my scss files:

.grey-footer {
    padding: 150px;
    border:20px solid red;
   @include breakpoint(medium) {
        padding:0;
        border:20px solid blue;
    }
}

My terminal reads:

[14:39:59] Starting 'styles'...
[14:39:59] assets/styles/scss/footer.scss
Error: no mixin named breakpoint
        on line 12 of assets/styles/scss/footer.scss
>>     @include breakpoint(medium) {

   -------------^

Are there additional configuration steps needed to get Foundations mixins for breakpoints imported into the project?

**Comment by garrett-eclipse** [comment] 2019-02-06 00:17
Hi @BenQuirk 

It appears you have setup a custom footer.scss file where you've used the breakpoint mixin. When you have a custom .scss file and want to use mixins, etc from Foundation you'll need to import the foundation components into your file otherwise yours won't have the required dependency. 

Take a look at the style.scss file - https://github.com/JeremyEnglert/JointsWP/blob/master/assets/styles/scss/style.scss
*Make sure your code follows the foundation includes.

You at minimum should include settings and foundation. Or if you need specific components instead then place in settings and you can get individual components like;
`@import "foundation/components/buttons";`


That being said if footer is to be included into all your pages you could just make it a partial by naming it _footer.scss and importing it into the base of your style.scss;
`@import 'footer';`
If you go to bottom of the style.scss you'll see this is how _global.scss is imported;
https://github.com/JeremyEnglert/JointsWP/blob/master/assets/styles/scss/style.scss#L68

Hope that helps.
I'm going to close this as it's not a bug in the theme but a customization. Feel free to reply if you still need help though as I'll be notified.

**Closed by garrett-eclipse** 2019-02-06 00:17 UTC

**Comment by BenQuirk** [comment] 2019-02-06 14:34
Many many thanks @garrett-eclipse  for your assistance.

**Comment by itsvishalpandey** [comment] 2021-01-19 15:16
![2021-01-19 (2)](https://user-images.githubusercontent.com/75249893/105053698-3f178680-5a97-11eb-9b6b-11e14e9ad469.png)
![2021-01-19 (3)](https://user-images.githubusercontent.com/75249893/105053744-4d65a280-5a97-11eb-8868-8dbffef11871.png)


how can i solve this error anyone suggest?

**Comment by garretthyder** [comment] 2021-01-19 23:22
In future @itsvishalpandey I would suggest opening a new ticket.

Your issue isn't really a JointsWP issue but more a SCSS implementation issue. Before you can use your mixins in another file you have to import the mixin file into the other one.
https://sass-lang.com/documentation/at-rules/import

**Comment by KarunaTz** [comment] 2021-02-10 09:29
I got the same error @itsvishalpandey  i also @import 'mixins' in file style.scss it still didn't work.

**Comment by garretthyder** [comment] 2021-02-10 17:17
@KarunaTz if you're using the mixin in the _global.scss or other partial you want to import your mixins into that partial file. Importing into style.scss won't import it for all partials, just the style.scss file.

**Comment by KarunaTz** [comment] 2021-02-12 13:22
I see thanks it works now !!!

**Comment by HectorGitt** [comment] 2022-05-04 12:00
Well the problem was the arrangements of the import, you should always keep mixin and functions imports at the top of the main file then other imports can follow so sass can easily locate the mixin before processing of other files.
