### ISSUE TITLE
WP-SCSS compiling errors

### ISSUE THREAD

**Issue by maplesyrupsucker** [JeremyEnglert/JointsWP#241] opened 2017-04-19 16:37 UTC
Has anyone else experienced issues compiling joints using wp-scss. Getting compiling errors that seem to change from time to time. It looks like issues with variables in flex grid and grid scss files.

It looks like scssphp has had this issue reported but no sign of life over there.

https://github.com/leafo/scssphp/issues/446

Compiling is working fine locally with codekit so likely just a 3rd party issue but if anyone has come across a simple fix would love to hear what they did!

**Comment by garrett-eclipse** [comment] 2017-04-19 16:56
Hi @corbinfraser 

I'm following that ticket as well hoping it gets attention at some point. In our theme we use a customized scssphp implementation that's similar to wp-scss and is affected by the same issue.

For now what we've done is compile the core scss via command line, and then so we can use scssphp when we save theme options we have an override.scss which is a duplicate but with grid and flex-grid commented out;
```
//@include foundation-grid;
//@include foundation-flex-classes;
//@include foundation-flex-grid;
```

This is a temporary solution as I'd like to drop the need for the duplication of css this creates but at least for now it'll get your foundation compiling.

I also heard mention that 6.3 foundation doesn't have this issue but haven't had a chance to check.

Hope that helps,
Cheers

**Comment by corbinfraser** [comment] 2017-04-19 17:01
Thanks @garrett-eclipse - I think we're stuck doing a similar workaround for the time being. Will be following to see if this gets resolved for good.

**Comment by garrett-eclipse** [comment] 2017-04-19 17:44
It is what it is sadly, if I had the time/ability would take a crack at it myself.

**Comment by JeremyEnglert** [comment] 2017-04-22 05:05
Hi guys,

Is this an issue with JointsWP 4 (current) or just version 5 (upcoming)?

**Comment by garrett-eclipse** [comment] 2017-04-24 18:16
Hi @JeremyEnglert this is for JointsWP 4 with Foundation 6.2.X. I believe the issue isn't present any longer with Foundation 6.3 but haven't confirmed.

**Comment by corbinfraser** [comment] 2017-04-24 18:49
Hi @JeremyEnglert - I just setup a local environment with Joints5 and tested wp-scss.  Unfortunatly ran into a compiling error

```
Sass Compiling Error

style.scss 
"Undefined mixin add-foundation-colors: line: 77"
```

Commenting that line out in _settings.scss returned this:

```
ass Compiling Error

style.scss 
"Undefined variable $primary-color: line: 144"
```

**Comment by AndrewSepic** [comment] 2017-09-14 18:58
@corbinfraser Check out this thread http://foundation.zurb.com/forum/posts/50975-issue-with-foundation-color-palette--primary-not-defined

**Comment by garrett-eclipse** [comment] 2017-11-23 05:18
Hi @maplesyrupsucker sorry I fully overlooked your reply.

Does your local environment hold the node_modules? you'll want to `npm install` on it to hold all dependencies within the WP install so that wp-scss can import them.

**Comment by JeremyEnglert** [comment] 2018-01-27 19:36
Closing out this issue. Please feel free to open if the issue still exists.

**Closed by JeremyEnglert** 2018-01-27 19:36 UTC
